# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libsmoldyn', [dirname(__file__)])
        except ImportError:
            import _libsmoldyn
            return _libsmoldyn
        if fp is not None:
            try:
                _mod = imp.load_module('_libsmoldyn', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libsmoldyn = swig_import_helper()
    del swig_import_helper
else:
    import _libsmoldyn
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


ECok = _libsmoldyn.ECok
ECnotify = _libsmoldyn.ECnotify
ECwarning = _libsmoldyn.ECwarning
ECnonexist = _libsmoldyn.ECnonexist
ECall = _libsmoldyn.ECall
ECmissing = _libsmoldyn.ECmissing
ECbounds = _libsmoldyn.ECbounds
ECsyntax = _libsmoldyn.ECsyntax
ECerror = _libsmoldyn.ECerror
ECmemory = _libsmoldyn.ECmemory
ECbug = _libsmoldyn.ECbug
ECsame = _libsmoldyn.ECsame
ECwildcard = _libsmoldyn.ECwildcard

def smolGetVersion():
  return _libsmoldyn.smolGetVersion()
smolGetVersion = _libsmoldyn.smolGetVersion

def smolSetLogging(*args):
  return _libsmoldyn.smolSetLogging(*args)
smolSetLogging = _libsmoldyn.smolSetLogging

def smolSetThrowing(*args):
  return _libsmoldyn.smolSetThrowing(*args)
smolSetThrowing = _libsmoldyn.smolSetThrowing

def smolSetError(*args):
  return _libsmoldyn.smolSetError(*args)
smolSetError = _libsmoldyn.smolSetError

def smolSetErrorNT(*args):
  return _libsmoldyn.smolSetErrorNT(*args)
smolSetErrorNT = _libsmoldyn.smolSetErrorNT

def smolGetError(*args):
  return _libsmoldyn.smolGetError(*args)
smolGetError = _libsmoldyn.smolGetError

def smolClearError():
  return _libsmoldyn.smolClearError()
smolClearError = _libsmoldyn.smolClearError

def smolSetDebugMode(*args):
  return _libsmoldyn.smolSetDebugMode(*args)
smolSetDebugMode = _libsmoldyn.smolSetDebugMode

def smolErrorCodeToString(*args):
  return _libsmoldyn.smolErrorCodeToString(*args)
smolErrorCodeToString = _libsmoldyn.smolErrorCodeToString

def smolNewSim(*args):
  return _libsmoldyn.smolNewSim(*args)
smolNewSim = _libsmoldyn.smolNewSim

def smolUpdateSim(*args):
  return _libsmoldyn.smolUpdateSim(*args)
smolUpdateSim = _libsmoldyn.smolUpdateSim

def smolRunTimeStep(*args):
  return _libsmoldyn.smolRunTimeStep(*args)
smolRunTimeStep = _libsmoldyn.smolRunTimeStep

def smolRunSim(*args):
  return _libsmoldyn.smolRunSim(*args)
smolRunSim = _libsmoldyn.smolRunSim

def smolRunSimUntil(*args):
  return _libsmoldyn.smolRunSimUntil(*args)
smolRunSimUntil = _libsmoldyn.smolRunSimUntil

def smolFreeSim(*args):
  return _libsmoldyn.smolFreeSim(*args)
smolFreeSim = _libsmoldyn.smolFreeSim

def smolDisplaySim(*args):
  return _libsmoldyn.smolDisplaySim(*args)
smolDisplaySim = _libsmoldyn.smolDisplaySim

def smolPrepareSimFromFile(*args):
  return _libsmoldyn.smolPrepareSimFromFile(*args)
smolPrepareSimFromFile = _libsmoldyn.smolPrepareSimFromFile

def smolLoadSimFromFile(*args):
  return _libsmoldyn.smolLoadSimFromFile(*args)
smolLoadSimFromFile = _libsmoldyn.smolLoadSimFromFile

def smolReadConfigString(*args):
  return _libsmoldyn.smolReadConfigString(*args)
smolReadConfigString = _libsmoldyn.smolReadConfigString

def smolSetSimTimes(*args):
  return _libsmoldyn.smolSetSimTimes(*args)
smolSetSimTimes = _libsmoldyn.smolSetSimTimes

def smolSetTimeStart(*args):
  return _libsmoldyn.smolSetTimeStart(*args)
smolSetTimeStart = _libsmoldyn.smolSetTimeStart

def smolSetTimeStop(*args):
  return _libsmoldyn.smolSetTimeStop(*args)
smolSetTimeStop = _libsmoldyn.smolSetTimeStop

def smolSetTimeNow(*args):
  return _libsmoldyn.smolSetTimeNow(*args)
smolSetTimeNow = _libsmoldyn.smolSetTimeNow

def smolSetTimeStep(*args):
  return _libsmoldyn.smolSetTimeStep(*args)
smolSetTimeStep = _libsmoldyn.smolSetTimeStep

def smolSetRandomSeed(*args):
  return _libsmoldyn.smolSetRandomSeed(*args)
smolSetRandomSeed = _libsmoldyn.smolSetRandomSeed

def smolSetPartitions(*args):
  return _libsmoldyn.smolSetPartitions(*args)
smolSetPartitions = _libsmoldyn.smolSetPartitions

def smolSetGraphicsParams(*args):
  return _libsmoldyn.smolSetGraphicsParams(*args)
smolSetGraphicsParams = _libsmoldyn.smolSetGraphicsParams

def smolSetTiffParams(*args):
  return _libsmoldyn.smolSetTiffParams(*args)
smolSetTiffParams = _libsmoldyn.smolSetTiffParams

def smolSetLightParams(*args):
  return _libsmoldyn.smolSetLightParams(*args)
smolSetLightParams = _libsmoldyn.smolSetLightParams

def smolSetBackgroundStyle(*args):
  return _libsmoldyn.smolSetBackgroundStyle(*args)
smolSetBackgroundStyle = _libsmoldyn.smolSetBackgroundStyle

def smolSetFrameStyle(*args):
  return _libsmoldyn.smolSetFrameStyle(*args)
smolSetFrameStyle = _libsmoldyn.smolSetFrameStyle

def smolSetGridStyle(*args):
  return _libsmoldyn.smolSetGridStyle(*args)
smolSetGridStyle = _libsmoldyn.smolSetGridStyle

def smolSetTextStyle(*args):
  return _libsmoldyn.smolSetTextStyle(*args)
smolSetTextStyle = _libsmoldyn.smolSetTextStyle

def smolAddTextDisplay(*args):
  return _libsmoldyn.smolAddTextDisplay(*args)
smolAddTextDisplay = _libsmoldyn.smolAddTextDisplay

def smolSetOutputPath(*args):
  return _libsmoldyn.smolSetOutputPath(*args)
smolSetOutputPath = _libsmoldyn.smolSetOutputPath

def smolAddOutputFile(*args):
  return _libsmoldyn.smolAddOutputFile(*args)
smolAddOutputFile = _libsmoldyn.smolAddOutputFile

def smolAddCommand(*args):
  return _libsmoldyn.smolAddCommand(*args)
smolAddCommand = _libsmoldyn.smolAddCommand

def smolAddCommandFromString(*args):
  return _libsmoldyn.smolAddCommandFromString(*args)
smolAddCommandFromString = _libsmoldyn.smolAddCommandFromString

def smolAddSpecies(*args):
  return _libsmoldyn.smolAddSpecies(*args)
smolAddSpecies = _libsmoldyn.smolAddSpecies

def smolGetSpeciesIndex(*args):
  return _libsmoldyn.smolGetSpeciesIndex(*args)
smolGetSpeciesIndex = _libsmoldyn.smolGetSpeciesIndex

def smolGetSpeciesIndexNT(*args):
  return _libsmoldyn.smolGetSpeciesIndexNT(*args)
smolGetSpeciesIndexNT = _libsmoldyn.smolGetSpeciesIndexNT

def smolGetSpeciesName(*args):
  return _libsmoldyn.smolGetSpeciesName(*args)
smolGetSpeciesName = _libsmoldyn.smolGetSpeciesName

def smolSetSpeciesMobility(*args):
  return _libsmoldyn.smolSetSpeciesMobility(*args)
smolSetSpeciesMobility = _libsmoldyn.smolSetSpeciesMobility

def smolAddMolList(*args):
  return _libsmoldyn.smolAddMolList(*args)
smolAddMolList = _libsmoldyn.smolAddMolList

def smolGetMolListIndex(*args):
  return _libsmoldyn.smolGetMolListIndex(*args)
smolGetMolListIndex = _libsmoldyn.smolGetMolListIndex

def smolGetMolListIndexNT(*args):
  return _libsmoldyn.smolGetMolListIndexNT(*args)
smolGetMolListIndexNT = _libsmoldyn.smolGetMolListIndexNT

def smolGetMolListName(*args):
  return _libsmoldyn.smolGetMolListName(*args)
smolGetMolListName = _libsmoldyn.smolGetMolListName

def smolSetMolList(*args):
  return _libsmoldyn.smolSetMolList(*args)
smolSetMolList = _libsmoldyn.smolSetMolList

def smolSetMaxMolecules(*args):
  return _libsmoldyn.smolSetMaxMolecules(*args)
smolSetMaxMolecules = _libsmoldyn.smolSetMaxMolecules

def smolAddSolutionMolecules(*args):
  return _libsmoldyn.smolAddSolutionMolecules(*args)
smolAddSolutionMolecules = _libsmoldyn.smolAddSolutionMolecules

def smolAddCompartmentMolecules(*args):
  return _libsmoldyn.smolAddCompartmentMolecules(*args)
smolAddCompartmentMolecules = _libsmoldyn.smolAddCompartmentMolecules

def smolAddSurfaceMolecules(*args):
  return _libsmoldyn.smolAddSurfaceMolecules(*args)
smolAddSurfaceMolecules = _libsmoldyn.smolAddSurfaceMolecules

def smolGetMoleculeCount(*args):
  return _libsmoldyn.smolGetMoleculeCount(*args)
smolGetMoleculeCount = _libsmoldyn.smolGetMoleculeCount

def smolSetMoleculeStyle(*args):
  return _libsmoldyn.smolSetMoleculeStyle(*args)
smolSetMoleculeStyle = _libsmoldyn.smolSetMoleculeStyle

def smolSetBoundaryType(*args):
  return _libsmoldyn.smolSetBoundaryType(*args)
smolSetBoundaryType = _libsmoldyn.smolSetBoundaryType

def smolAddSurface(*args):
  return _libsmoldyn.smolAddSurface(*args)
smolAddSurface = _libsmoldyn.smolAddSurface

def smolGetSurfaceIndex(*args):
  return _libsmoldyn.smolGetSurfaceIndex(*args)
smolGetSurfaceIndex = _libsmoldyn.smolGetSurfaceIndex

def smolGetSurfaceIndexNT(*args):
  return _libsmoldyn.smolGetSurfaceIndexNT(*args)
smolGetSurfaceIndexNT = _libsmoldyn.smolGetSurfaceIndexNT

def smolGetSurfaceName(*args):
  return _libsmoldyn.smolGetSurfaceName(*args)
smolGetSurfaceName = _libsmoldyn.smolGetSurfaceName

def smolSetSurfaceAction(*args):
  return _libsmoldyn.smolSetSurfaceAction(*args)
smolSetSurfaceAction = _libsmoldyn.smolSetSurfaceAction

def smolSetSurfaceRate(*args):
  return _libsmoldyn.smolSetSurfaceRate(*args)
smolSetSurfaceRate = _libsmoldyn.smolSetSurfaceRate

def smolAddPanel(*args):
  return _libsmoldyn.smolAddPanel(*args)
smolAddPanel = _libsmoldyn.smolAddPanel

def smolGetPanelIndex(*args):
  return _libsmoldyn.smolGetPanelIndex(*args)
smolGetPanelIndex = _libsmoldyn.smolGetPanelIndex

def smolGetPanelIndexNT(*args):
  return _libsmoldyn.smolGetPanelIndexNT(*args)
smolGetPanelIndexNT = _libsmoldyn.smolGetPanelIndexNT

def smolGetPanelName(*args):
  return _libsmoldyn.smolGetPanelName(*args)
smolGetPanelName = _libsmoldyn.smolGetPanelName

def smolSetPanelJump(*args):
  return _libsmoldyn.smolSetPanelJump(*args)
smolSetPanelJump = _libsmoldyn.smolSetPanelJump

def smolAddSurfaceUnboundedEmitter(*args):
  return _libsmoldyn.smolAddSurfaceUnboundedEmitter(*args)
smolAddSurfaceUnboundedEmitter = _libsmoldyn.smolAddSurfaceUnboundedEmitter

def smolSetSurfaceSimParams(*args):
  return _libsmoldyn.smolSetSurfaceSimParams(*args)
smolSetSurfaceSimParams = _libsmoldyn.smolSetSurfaceSimParams

def smolAddPanelNeighbor(*args):
  return _libsmoldyn.smolAddPanelNeighbor(*args)
smolAddPanelNeighbor = _libsmoldyn.smolAddPanelNeighbor

def smolSetSurfaceStyle(*args):
  return _libsmoldyn.smolSetSurfaceStyle(*args)
smolSetSurfaceStyle = _libsmoldyn.smolSetSurfaceStyle

def smolAddCompartment(*args):
  return _libsmoldyn.smolAddCompartment(*args)
smolAddCompartment = _libsmoldyn.smolAddCompartment

def smolGetCompartmentIndex(*args):
  return _libsmoldyn.smolGetCompartmentIndex(*args)
smolGetCompartmentIndex = _libsmoldyn.smolGetCompartmentIndex

def smolGetCompartmentIndexNT(*args):
  return _libsmoldyn.smolGetCompartmentIndexNT(*args)
smolGetCompartmentIndexNT = _libsmoldyn.smolGetCompartmentIndexNT

def smolGetCompartmentName(*args):
  return _libsmoldyn.smolGetCompartmentName(*args)
smolGetCompartmentName = _libsmoldyn.smolGetCompartmentName

def smolAddCompartmentSurface(*args):
  return _libsmoldyn.smolAddCompartmentSurface(*args)
smolAddCompartmentSurface = _libsmoldyn.smolAddCompartmentSurface

def smolAddCompartmentPoint(*args):
  return _libsmoldyn.smolAddCompartmentPoint(*args)
smolAddCompartmentPoint = _libsmoldyn.smolAddCompartmentPoint

def smolAddCompartmentLogic(*args):
  return _libsmoldyn.smolAddCompartmentLogic(*args)
smolAddCompartmentLogic = _libsmoldyn.smolAddCompartmentLogic

def smolAddReaction(*args):
  return _libsmoldyn.smolAddReaction(*args)
smolAddReaction = _libsmoldyn.smolAddReaction

def smolGetReactionIndex(*args):
  return _libsmoldyn.smolGetReactionIndex(*args)
smolGetReactionIndex = _libsmoldyn.smolGetReactionIndex

def smolGetReactionIndexNT(*args):
  return _libsmoldyn.smolGetReactionIndexNT(*args)
smolGetReactionIndexNT = _libsmoldyn.smolGetReactionIndexNT

def smolGetReactionName(*args):
  return _libsmoldyn.smolGetReactionName(*args)
smolGetReactionName = _libsmoldyn.smolGetReactionName

def smolSetReactionRate(*args):
  return _libsmoldyn.smolSetReactionRate(*args)
smolSetReactionRate = _libsmoldyn.smolSetReactionRate

def smolSetReactionRegion(*args):
  return _libsmoldyn.smolSetReactionRegion(*args)
smolSetReactionRegion = _libsmoldyn.smolSetReactionRegion

def smolSetReactionProducts(*args):
  return _libsmoldyn.smolSetReactionProducts(*args)
smolSetReactionProducts = _libsmoldyn.smolSetReactionProducts

def smolAddPort(*args):
  return _libsmoldyn.smolAddPort(*args)
smolAddPort = _libsmoldyn.smolAddPort

def smolGetPortIndex(*args):
  return _libsmoldyn.smolGetPortIndex(*args)
smolGetPortIndex = _libsmoldyn.smolGetPortIndex

def smolGetPortIndexNT(*args):
  return _libsmoldyn.smolGetPortIndexNT(*args)
smolGetPortIndexNT = _libsmoldyn.smolGetPortIndexNT

def smolGetPortName(*args):
  return _libsmoldyn.smolGetPortName(*args)
smolGetPortName = _libsmoldyn.smolGetPortName

def smolAddPortMolecules(*args):
  return _libsmoldyn.smolAddPortMolecules(*args)
smolAddPortMolecules = _libsmoldyn.smolAddPortMolecules

def smolGetPortMolecules(*args):
  return _libsmoldyn.smolGetPortMolecules(*args)
smolGetPortMolecules = _libsmoldyn.smolGetPortMolecules

def smolAddLattice(*args):
  return _libsmoldyn.smolAddLattice(*args)
smolAddLattice = _libsmoldyn.smolAddLattice

def smolAddLatticePort(*args):
  return _libsmoldyn.smolAddLatticePort(*args)
smolAddLatticePort = _libsmoldyn.smolAddLatticePort

def smolAddLatticeSpecies(*args):
  return _libsmoldyn.smolAddLatticeSpecies(*args)
smolAddLatticeSpecies = _libsmoldyn.smolAddLatticeSpecies

def smolGetLatticeIndex(*args):
  return _libsmoldyn.smolGetLatticeIndex(*args)
smolGetLatticeIndex = _libsmoldyn.smolGetLatticeIndex

def smolGetLatticeIndexNT(*args):
  return _libsmoldyn.smolGetLatticeIndexNT(*args)
smolGetLatticeIndexNT = _libsmoldyn.smolGetLatticeIndexNT

def smolGetLatticeName(*args):
  return _libsmoldyn.smolGetLatticeName(*args)
smolGetLatticeName = _libsmoldyn.smolGetLatticeName

def smolAddLatticeMolecules(*args):
  return _libsmoldyn.smolAddLatticeMolecules(*args)
smolAddLatticeMolecules = _libsmoldyn.smolAddLatticeMolecules

def smolAddLatticeReaction(*args):
  return _libsmoldyn.smolAddLatticeReaction(*args)
smolAddLatticeReaction = _libsmoldyn.smolAddLatticeReaction
# This file is compatible with both classic and new-style classes.


