name: vcell support

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install cmake libjpeg-dev libtiff-dev freeglut3-dev libxi-dev libxmu-dev python3-dev
          sudo apt -y install libvtk9-dev vtk9
          sudo apt -y install xvfb
      - name: Configure smoldyn
        run: |
          cmake --version
          python -c "import sys; print(sys.version)"
          python -m pip install pytest matplotlib numpy wheel flaky setuptools uv
          mkdir build && cd build
          cmake -DOPTION_PYTHON=ON \
              -DOPTION_EXAMPLES=ON \
              -DOPTION_VCELL=ON \
              -DPython3_EXECUTABLE=$PYTHON \
              ..
      - name: Build smoldyn
        run: |
          cd build && cmake --build . && ctest --output-on-failure
